/**
 * PDF Report Generator for Audit Reports
 *
 * Generates a structured PDF report with the following sections:
 * - Cover page
 * - Executive summary
 * - Findings by framework
 * - SOX control matrix
 * - Trial balance summary
 */

export interface PDFReportData {
  engagement: {
    id: string;
    name: string;
    entityName: string;
    fiscalYearEnd: string;
    status: string;
    materialityThreshold: number;
    industry?: string | null;
    entityType?: string | null;
  };
  findings: Array<{
    ruleId: string;
    framework: string;
    severity: string;
    title: string;
    description: string;
    citation: string;
    remediation: string;
    amountImpact: number | null;
    status: string;
    createdAt: string;
  }>;
  controls: Array<{
    controlId: string;
    title: string;
    description: string;
    controlType: string;
    category: string;
    frequency: string;
    status: string;
    riskLevel: string;
  }>;
  accounts: Array<{
    accountNumber: string;
    accountName: string;
    accountType: string;
    beginningBalance: number;
    endingBalance: number;
  }>;
  generatedBy: string;
  generatedAt: string;
}

export interface PDFSection {
  title: string;
  content: string;
}

/**
 * Generate a structured text-based PDF report.
 * This creates a formatted document suitable for PDF rendering.
 */
export function generateAuditReport(data: PDFReportData): string {
  const sections: string[] = [];

  // Cover Page
  sections.push(formatCoverPage(data));

  // Executive Summary
  sections.push(formatExecutiveSummary(data));

  // Findings Detail by Framework
  for (const fw of ['GAAP', 'IRS', 'SOX', 'PCAOB']) {
    const fwFindings = data.findings.filter((f) => f.framework === fw);
    if (fwFindings.length > 0) {
      sections.push(formatFrameworkFindings(fw, fwFindings, data.engagement.materialityThreshold));
    }
  }

  // SOX Control Matrix
  if (data.controls.length > 0) {
    sections.push(formatSOXControlMatrix(data.controls));
  }

  // Trial Balance Summary
  if (data.accounts.length > 0) {
    sections.push(formatTrialBalanceSummary(data.accounts));
  }

  // Appendix — Methodology
  sections.push(formatMethodology());

  return sections.join('\n\n' + '='.repeat(80) + '\n\n');
}

function formatCoverPage(data: PDFReportData): string {
  return `
AUDIT REPORT
${'='.repeat(60)}

Entity:              ${data.engagement.entityName}
Engagement:          ${data.engagement.name}
Fiscal Year End:     ${data.engagement.fiscalYearEnd}
Industry:            ${data.engagement.industry || 'Not specified'}
Entity Type:         ${data.engagement.entityType || 'Not specified'}
Status:              ${data.engagement.status}
Materiality:         $${data.engagement.materialityThreshold.toLocaleString()}

Report Generated:    ${data.generatedAt}
Generated By:        ${data.generatedBy}

CONFIDENTIAL — FOR INTERNAL USE ONLY
  `.trim();
}

function formatExecutiveSummary(data: PDFReportData): string {
  const total = data.findings.length;
  const critical = data.findings.filter((f) => f.severity === 'critical').length;
  const high = data.findings.filter((f) => f.severity === 'high').length;
  const medium = data.findings.filter((f) => f.severity === 'medium').length;
  const low = data.findings.filter((f) => f.severity === 'low').length;
  const info = data.findings.filter((f) => f.severity === 'info').length;

  const gaap = data.findings.filter((f) => f.framework === 'GAAP').length;
  const irs = data.findings.filter((f) => f.framework === 'IRS').length;
  const sox = data.findings.filter((f) => f.framework === 'SOX').length;
  const pcaob = data.findings.filter((f) => f.framework === 'PCAOB').length;

  const totalImpact = data.findings
    .filter((f) => f.amountImpact)
    .reduce((sum, f) => sum + (f.amountImpact || 0), 0);

  const materialWeaknesses = data.controls.filter(
    (c) => c.status === 'material_weakness'
  ).length;
  const significantDeficiencies = data.controls.filter(
    (c) => c.status === 'significant_deficiency'
  ).length;

  return `
EXECUTIVE SUMMARY
${'='.repeat(60)}

FINDINGS OVERVIEW
  Total Findings:            ${total}
  Critical:                  ${critical}
  High:                      ${high}
  Medium:                    ${medium}
  Low:                       ${low}
  Informational:             ${info}

BY FRAMEWORK
  GAAP (ASC):                ${gaap}
  IRS / Tax Code:            ${irs}
  SOX 302/404:               ${sox}
  PCAOB Standards:           ${pcaob}

FINANCIAL IMPACT
  Total Estimated Impact:    $${totalImpact.toLocaleString()}
  Materiality Threshold:     $${data.engagement.materialityThreshold.toLocaleString()}
  Impact vs Materiality:     ${totalImpact > data.engagement.materialityThreshold ? 'EXCEEDS MATERIALITY' : 'Within materiality'}

INTERNAL CONTROLS
  Material Weaknesses:       ${materialWeaknesses}
  Significant Deficiencies:  ${significantDeficiencies}
  Controls Tested:           ${data.controls.length}
  Effective Controls:        ${data.controls.filter((c) => c.status === 'effective').length}
  `.trim();
}

function formatFrameworkFindings(
  framework: string,
  findings: PDFReportData['findings'],
  materiality: number
): string {
  const frameworkLabels: Record<string, string> = {
    GAAP: 'GAAP (ASC) Findings',
    IRS: 'IRS / Tax Code Findings',
    SOX: 'SOX 302/404 Findings',
    PCAOB: 'PCAOB Standards Findings',
  };

  let output = `\n${frameworkLabels[framework] || framework}\n${'='.repeat(60)}\n`;

  const sorted = [...findings].sort((a, b) => {
    const order: Record<string, number> = { critical: 0, high: 1, medium: 2, low: 3, info: 4 };
    return (order[a.severity] || 5) - (order[b.severity] || 5);
  });

  for (const f of sorted) {
    const material = f.amountImpact && f.amountImpact > materiality ? ' [MATERIAL]' : '';
    output += `
  ${f.severity.toUpperCase()}${material}: ${f.title}
  Rule: ${f.ruleId}
  Citation: ${f.citation}
  Status: ${f.status}
  ${f.amountImpact ? `Amount Impact: $${f.amountImpact.toLocaleString()}` : ''}
  Description: ${f.description}
  Remediation: ${f.remediation}
  ${'-'.repeat(40)}`;
  }

  return output;
}

function formatSOXControlMatrix(
  controls: PDFReportData['controls']
): string {
  let output = `\nSOX CONTROL MATRIX\n${'='.repeat(60)}\n`;

  const byCategory = new Map<string, typeof controls>();
  for (const c of controls) {
    const list = byCategory.get(c.category) || [];
    list.push(c);
    byCategory.set(c.category, list);
  }

  for (const [category, ctrls] of Array.from(byCategory.entries())) {
    output += `\n  Category: ${category.replace(/_/g, ' ').toUpperCase()}\n`;
    for (const c of ctrls) {
      output += `    ${c.controlId} | ${c.title} | ${c.controlType} | ${c.frequency} | ${c.status} | Risk: ${c.riskLevel}\n`;
    }
  }

  return output;
}

function formatTrialBalanceSummary(
  accounts: PDFReportData['accounts']
): string {
  let output = `\nTRIAL BALANCE SUMMARY\n${'='.repeat(60)}\n`;

  const types = ['asset', 'liability', 'equity', 'revenue', 'expense'];
  for (const type of types) {
    const typeAccounts = accounts.filter((a) => a.accountType === type);
    if (typeAccounts.length === 0) continue;

    const totalBeginning = typeAccounts.reduce((s, a) => s + a.beginningBalance, 0);
    const totalEnding = typeAccounts.reduce((s, a) => s + a.endingBalance, 0);

    output += `\n  ${type.toUpperCase()} (${typeAccounts.length} accounts)\n`;
    output += `    Beginning Balance: $${totalBeginning.toLocaleString()}\n`;
    output += `    Ending Balance:    $${totalEnding.toLocaleString()}\n`;
    output += `    Change:            $${(totalEnding - totalBeginning).toLocaleString()}\n`;
  }

  return output;
}

function formatMethodology(): string {
  return `
APPENDIX: METHODOLOGY
${'='.repeat(60)}

This audit report was generated using AuditPro's automated compliance analysis engine.

FRAMEWORKS APPLIED:
  - GAAP (ASC): US Generally Accepted Accounting Principles per ASC codification
  - IRS: Internal Revenue Code compliance checks
  - SOX 302/404: Sarbanes-Oxley internal control assessment
  - PCAOB: Public Company Accounting Oversight Board standards

ANALYSIS TECHNIQUES:
  - Benford's Law first and second digit analysis
  - Statistical anomaly detection (Z-score, IQR)
  - Financial ratio analysis (liquidity, profitability, leverage, efficiency)
  - Trend and variance analysis
  - Journal entry testing (weekend/holiday, round numbers, segregation of duties)

MATERIALITY:
  - Quantitative threshold applied as configured per engagement
  - Qualitative factors assessed by rule-specific logic

LIMITATIONS:
  - This automated analysis supplements but does not replace professional judgment
  - Findings should be reviewed by qualified audit professionals
  - Sample-based testing may not detect all issues
  `.trim();
}
